# Generated by Django 3.2 on 2021-12-15 12:33

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('national_code', models.PositiveBigIntegerField(unique=True, validators=[user.validators.validate_national_code])),
                ('age', models.PositiveSmallIntegerField(validators=[user.validators.validate_age])),
                ('total_toll_paid', models.PositiveBigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
